### ISSUE TITLE
[Bug] discord link does not work

### ISSUE THREAD

**Issue by endergirl3215** [EnderBro123/EndersHub-IssueTracker#10]
***DO NOT REMOVE THIS TEMPLATE OR YOUR ISSUE WILL BE CLOSED AND IGNORED.***

**Describe the bug**
A clear and concise description of what the bug i
The discord link in the github does not wirk

**Have you attempted to read the crash report before opening this issue?**
Put an X in Yes or No. If you select no, then don't worry. I'll let you know
where the issue is coming from, then your on your own from there.

[] Yes.
[] No.

**USE PASTEBIN. DO NOT DIRECTLY UPLOAD THE CRASH REPORT FILE.**
**To Reproduce**

**Expected behavior**

**Screenshots**

**Modpack Version**
Give us the version of the modpack your having issues with.

**Additional context**

**Checklist**
Put an X in each of the [] if you agree with these 3 things.

[] - I agree that I will not get any support from mods that have updated to 1.13x versions and do not support 1.12.
[] - I agree that I will not receive *ANY* support if I modified the modpack at all.
[] - I have read the Pinned Issue.
[] - I followed the template and gave as much info as I could.

**Comment by EnderBro123** [comment]
Fixed.
